Feature sergey lyubimov
see1rg/telegram_team pull request #15
Opened 2023-04-01 10:36 UTC by see1rg

Накидал service и repository

2023-04-01 18:45 UTC, akmeevd commented on src/main/java/com/skypro/telegram_team/controllers/AnimalController.java
> +        return animalService.deleteById(id);
можно del убрать в названии эндпоинта

2023-04-01 18:45 UTC, akmeevd commented on src/main/java/com/skypro/telegram_team/controllers/ReportController.java
> +    public Report deleteReport(@PathVariable Long id) {
можно del убрать в названии эндпоинта

2023-04-01 18:45 UTC, akmeevd commented on src/main/java/com/skypro/telegram_team/controllers/ReportController.java
> +//    public Report updateReport(@RequestBody Report report, @PathVariable Long id) {
здесь pathvariable нужно убрать, там id будет указываться в теле и по нему будут меняться другие параметры

2023-04-01 18:45 UTC, akmeevd commented on src/main/java/com/skypro/telegram_team/controllers/UserController.java
> +//    public User updateUser(@RequestBody User user, @PathVariable Long id) {
здесь pathvariable нужно убрать, там id будет указываться в теле и по нему будут меняться другие параметры

2023-04-01 18:45 UTC, akmeevd commented on src/main/java/com/skypro/telegram_team/services/ReportService.java
> +//    public Report update(Report report) {
здеcь должен быть метод save репозитория

2023-04-01 18:45 UTC, akmeevd commented on src/main/java/com/skypro/telegram_team/services/UserService.java
> +//        log.info("Updating user: " + user);
здеcь должен быть метод save репозитория

2023-04-01 18:45 UTC, akmeevd commented on src/main/java/com/skypro/telegram_team/services/AnimalService.java
> +//    public Animal update(Animal animal) {
здеcь должен быть метод save репозитория

2023-04-02 09:26 UTC, 11th requested changes

2023-04-02 09:26 UTC, 11th commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
Здесь должно быть validate

2023-04-02 09:26 UTC, 11th commented on src/main/resources/application.properties
Мне кажется или ты затрешь мои изменения в этом файле? 
Сейчас он выглядит так:
![IMAGE 2023-04-02 12:24:08](https://user-images.githubusercontent.com/46165284/229344203-b53ea82d-7f89-44d0-88d9-82db9b3b22e9.jpg)

2023-04-02 09:35 UTC, see1rg commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
Пока настройка будет create, пускай старые записи затираются.

2023-04-02 09:35 UTC, see1rg commented on src/main/resources/application.properties
Теперь ничего не пропадет😉

2023-04-02 09:41 UTC, 11th approved these changes

2023-04-02 10:00 UTC, merged