Feature sergey lyubimov
see1rg/telegram_team pull request #26
Opened 2023-04-06 17:00 UTC by see1rg

добавил логгирование в файл и enum User & Animal

2023-04-06 21:27 UTC, 11th requested changes

2023-04-06 21:27 UTC, 11th commented on src/main/resources/liquibase/scripts/scheme.sql
> -    status        VARCHAR(10),
не нужно править уже существующие миграции, иначе у того кто запустит приложение впервые не пройдет весь процесс миграций

2023-04-06 21:28 UTC, see1rg commented on src/main/resources/liquibase/scripts/scheme.sql
> -    status        VARCHAR(10),
Да, согласен, но я поздно сообразил.

2023-04-07 06:59 UTC, 11th commented on src/main/resources/liquibase/scripts/scheme.sql
> -    status        VARCHAR(10),
Нужно вернуть эту строчку и оставить changeSet который добавил

2023-04-07 07:03 UTC, 11th commented on src/main/resources/liquibase/scripts/scheme.sql
> -    status        VARCHAR(10),
нужно вернуть эту строчку

2023-04-07 07:06 UTC, 11th commented on src/main/resources/liquibase/scripts/scheme.sql
> +    ADD COLUMN status VARCHAR(10);
а эти нужно убрать
ALTER TABLE animals
    ADD COLUMN status VARCHAR(10);

Иначе у меня например не запустится приложение, так как не отработает этот changeSet, потому что поле status уже есть в Animals

2023-04-07 15:35 UTC, 11th approved these changes

2023-04-07 15:35 UTC, 11th commented on src/main/java/com/skypro/telegram_team/services/AnimalService.java
> +    public List<Animal> findAllByUserIdNotNullAndState(Animal.AnimalStateEnum inTest) {
А почему не добавил javadoc?

2023-04-07 15:35 UTC, 11th commented on src/main/java/com/skypro/telegram_team/timer/Timer.java
> +                    "Последний отчет был написан более двух дней у :" + user.getName() + " " + user.getSurname());
разве это уведомление не должно отправляться самому юзеру?

2023-04-07 20:07 UTC, merged